---
epochs: 30

# 3 for kuramoto and 4 for spring and charged.
n_momenta: 4

n_blocks: 3
dim_feedforward: 512
n_layers_mlp: 2
n_additional_mlp_layers: 2
n_final_mlp_layers: 2


# Scale the loss to avoid gradient explosion.
dropout_rate: 0.2
learning_rate: 0.002 #0.00025
learning_rate_decay: 200
gamma: 0.5
batch_size: 5