---
epochs: 10

# 3 for kuramoto and 4 for spring and charged.
n_momenta: 4

# N_HID: 120
n_hid: 512
INPUT_EMB_HID: 128
# Dimension of hidden layers of attention mechanisms.
EMB_HID: 256
ATT_HID: 256
# SKIP: True
# Soft constraint for symmetry.
REG: 0.
NO_REG: False
# Hard constraint for symmetry.
SYM: False

# Scale the loss to avoid gradient explosion.
dropout_rate: 0
learning_rate: 0.05 #0.00025
learning_rate_decay: 200
gamma: 0.5
batch_size: 10

TIMESTEPS: 1
TEMP: 0.5
# NOTE: 10 for kuramoto, 100 for spring and charged.
INTERVAL: 10
SAMPLES: 100

# Run n rounds of the code.
ROUNDS: 1
TEMP: 0.5
