---
# General
model_sel: "sqgnn"
post_model_sel: "pqgnn" # only for split training
n_momenta: 4

# Classical
epochs: 20
normalize: True
dim_feedforward: 6
batchnorm: True

dropout_rate: 0.3
learning_rate: 0.01
learning_rate_decay: 200
gamma: 0.5
batch_size: 5

# GNN
n_blocks: 3
n_layers_mlp: 2 # initial mlp layers before the blocks
n_additional_mlp_layers: 0 # additional layers within a block
n_final_mlp_layers: 2 # layers after the blocks
factor: True
tokenize: -1
embedding_dims: -1
symmetrize: True

# Quantum
data_reupload: True

# PyTorch
detect_anomaly: False # enables torch' anomaly detector
device: 'cpu' # anything but 'cpu' to use cuda devices instead

# MLFLOW
plot_mode: "train"
git_hash_identifier: "git_hash"