---
# General
model_sel: "sqgnn"
post_model_sel: "pqgnn" # only for split training
n_momenta: 4

# Classical
epochs: 20
normalize: True
dim_feedforward: 6
dim_feedforward_range: [4, 256, "log"]
batchnorm: True

dropout_rate: 0.3
dropout_rate_range: [0.1, 1.0, "linear"]
learning_rate: 0.01
learning_rate_range: [1e-5, 1e-1, "log"]
learning_rate_decay: 200
learning_rate_decay_range: [1, 1000, "log"]
gamma: 0.5
batch_size: 5
batch_size_range: [1, 64, "log"]

# GNN
n_blocks: 3
n_blocks_range: [1, 5, "linear"]
n_layers_mlp: 2 # initial mlp layers before the blocks
n_layers_mlp_range: [1, 5, "linear"]
n_additional_mlp_layers: 0 # additional layers within a block
n_additional_mlp_layers_range: [1, 5, "linear"]
n_final_mlp_layers: 2 # layers after the blocks
n_final_mlp_layers_range: [1, 5, "linear"]
factor: True
tokenize: -1
embedding_dims: -1
symmetrize: True

# Quantum
data_reupload: True
data_reupload_range: [True, False]

# PyTorch
detect_anomaly: False # enables torch' anomaly detector
device: 'cpu' # anything but 'cpu' to use cuda devices instead

# MLFLOW
plot_mode: "train"
git_hash_identifier: "git_hash"