---
epochs: 20

# 3 for kuramoto and 4 for spring and charged.
n_momenta: 4

# N_HID: 120
n_hid: 512
INPUT_EMB_HID: 128
# Dimension of hidden layers of attention mechanisms.
EMB_HID: 256
ATT_HID: 256
# SKIP: True
# Soft constraint for symmetry.
REG: 0.
NO_REG: False
# Hard constraint for symmetry.
SYM: False

# Scale the loss to avoid gradient explosion.
dropout_rate: 0.1
learning_rate: 0.002 #0.00025
learning_rate_decay: 200
gamma: 0.5
batch_size: 5